### ISSUE TITLE
Feature request: Display counts as stacks and units or whole numbers.

### ISSUE THREAD

**Issue by PlNG** [AsherGlick/ResourceCalculator#1]

**Comment by AsherGlick** [comment]
I am not exactly sure what you mean by this. Can you give me an example of what it would look like?

**Comment by PlNG** [comment]
Like how another site shows this information.
![image](https://user-images.githubusercontent.com/109932/54871440-1bdffb00-4d8a-11e9-8f41-56a7610b5dca.png)
9x64+24 can be easier to parse just how much you need than 600.

**Comment by AsherGlick** [comment]
This can now be done via the new text instructions system for any calculator page that has stack sizes defined.
![Screenshot from 2019-05-23 08-22-53](https://user-images.githubusercontent.com/603989/58252463-2a1fa880-7d34-11e9-8415-2b0356b84fd2.png)
