### ISSUE TITLE
1.20

### ISSUE THREAD

**Issue by Jackuhlf** [AsherGlick/ResourceCalculator#110]
How do i use this for 1.20 blocks and items?

**Comment by AsherGlick** [comment]
Looks like i never merged #107... Ill probably have time to do that over the weekend.

**Comment by Jackuhlf** [comment]
is there a separate website for it?

**Comment by 3agithub** [comment]
still no update? the 1.21 development cycle is about to begin - hope this gets merged soon

**Comment by Jackuhlf** [comment]
If I knew how to update it myself via video tutorial instead of reading the minimal instructions then I’d gladly do it.

**Comment by AsherGlick** [comment]
I believe it is mostly done in #107, it still needs to be reviewed to make sure it is correct and that nothing is broken. I don't get to play Minecraft much anymore and the site brings in only a few cents a day over the cost of the servers. So it is difficult to prioritize this project's tasks against other tasks that do bring enjoyment or financing.

**Comment by Jackuhlf** [comment]
What do i do with that file

**Comment by Jackuhlf** [comment]
Is there a good video on how to put this site onto Docker? Ive gone thru 5+ videos and have no clue whats happening.

**Comment by AsherGlick** [comment]
#107 is merged. Should be live soon. Only a few weeks after 1.21 released.
