### ISSUE TITLE
"Grass" got renamed to "Short Grass"

### ISSUE THREAD

**Issue by Meliadolin** [AsherGlick/ResourceCalculator#131]
Grass got renamed to Short Grass in-game.
When importing a list from litematica, it doesn't read anything after the incorrectly named block.
Block names should be updated accordingly to prevent this.

**Comment by AsherGlick** [comment]
The only renamed block in 1.21! Guess I took some shortcuts when getting the new recipe data and ignored all the blocks that did not have. Nice catch.
