### ISSUE TITLE
Suggestion: add inventory of already owned resources, that can be used

### ISSUE THREAD

**Issue by mmodrow** [AsherGlick/ResourceCalculator#22]
Example: I want to craft 20 bookshelves in minecraft. To do so I need books and planks. To craft books I need paper and leather, to craft paper I need sugar cane.

If I already own a couple of books and papers, I will need drastically less sugar cane.

Would be great to have that covered as well.

If you'd like the idea, I would try to implement it, as it would make a project idea, that I had for quite some time, pretty much obsolete.

**Comment by AsherGlick** [comment]
This sounds like a fine feature to add. In fact you can sort of get away with it today by putting in negative numbers on the resources you already have.

https://resourcecalculator.com/minecraft/#bookshelf=20
![Screenshot from 2021-04-18 11-29-41](https://user-images.githubusercontent.com/603989/115153058-921ebc80-a039-11eb-8a8a-832a28a09ea8.png)

https://resourcecalculator.com/minecraft/#bookshelf=20&paper=-5&book=-6
![Screenshot from 2021-04-18 11-29-30](https://user-images.githubusercontent.com/603989/115153062-94811680-a039-11eb-95a1-e4e8dca2bf7a.png)

This is definitely a case of a bug being a feature though. I think at the very least negative numbers can be better supported in the chart, text instructions, and not hidden by `hide unused`. If you have a good idea for how this should be implemented I'll be happy to listen. The major consideration here is keeping it as simple and discoverable as possible on both desktop and mobile, and across all different calculators.

**Comment by mmodrow** [comment]
My first intuition would have been to clone the resource table in the build process and hide it behind an "inventory" button, which gets persisted in the URI with a prefix on each resource. It would interact exactly like the current resource table and in the text it could say something like "Take <amount> <item> from inventory."

But I have not given it a deeper thought, yet. I wanted to query your opinion first.

**Comment by AsherGlick** [comment]
I would be wary of cloning the entire table as that will increase the size of the web page dramatically and make it load more slowly, especially on lower end mobile. I have some speed/size improvements sitting on the `dev` branch to further improve the current size. I think this merits some more thought about what the use cases of this feature are to figure out how it should be implemented. EG: is an inventory something that you would want persisted between different calculations? So that you can follow a link from a website and see only the delta you need? If so maybe it should be stored in `localstorage` instead of the uri. Ill do some thinking on my end in parallel but in general I think the ability to say "but I have this resource please exclude it from the calculation" is a feature I would like to have.

**Comment by mmodrow** [comment]
In this case I will work on the logic and the display for the calculation first and think about how to manage the inventory later on. I guess putting the inventory into local storage with the option of JSON import/export should be a good in-dev crutch to get around this issue while having a benefit for the final version.

**Comment by mmodrow** [comment]
I did some experiments over in my fork at [mmodrow/ResourceCalculator](https://github.com/mmodrow/ResourceCalculator/tree/features/add_inventory).

Currently I have not created an UI for changing the inventory content, but I made the inventory read/write local storage and use inventory items in the calculations and the output.

http://127.0.0.1:8080/minecraft/#darkoakfence=20
LocalStorage:
`[Inventory] = {"Dark Oak Wood Planks":3,"Oak Wood Planks":5}`
![image](https://user-images.githubusercontent.com/11810519/116999687-41b58900-ace0-11eb-9016-bd84a444f9ee.png)

For changing the inventory I am thinking about adding to the double-click-menu, where the user can change the recipe.

Do you have any thoughts on this approach?

**Comment by mmodrow** [comment]
Inventory items can also be used in later stages of the build with this implementation:
http://127.0.0.1:8080/minecraft/#lectern=3
`[minecraft Inventory] = {Oak Wood Planks":5,"Book":1,"Paper":2,"Bookshelf":1}`
![image](https://user-images.githubusercontent.com/11810519/117010283-f0f85d00-acec-11eb-99ba-3c4f1d6692b4.png)

**Comment by mmodrow** [comment]
Honing in:
`[minecraft Inventory] = {"Oak Wood Planks":5,"Book":1,"Paper":100,"Bookshelf":1}`
http://127.0.0.1:8080/minecraft/#anvil=3
![image](https://user-images.githubusercontent.com/11810519/117223164-60fe0480-ae0d-11eb-814c-d4de2ef0cf1f.png)
http://127.0.0.1:8080/minecraft/#lectern=30
![image](https://user-images.githubusercontent.com/11810519/117223257-94409380-ae0d-11eb-979a-10e3cca43f62.png)


(never mind the small icon on the right edge - that's a local extension, no change to the site.)

**Comment by AsherGlick** [comment]
I like how it is shaping up. Breaking up the sections for "Missing" and "Owned" definitely helps make it clear what the program is doing. Looking forward to see your vision on how to make adding/removing items from the inventory work well.

**Comment by mmodrow** [comment]
Just in case, the @AsherGlick mention in the PR didn't cause a notification: the PR is ready for review.
