### ISSUE TITLE
Stonecutter recipes incomplete

### ISSUE THREAD

**Issue by HyperBeast43** [AsherGlick/ResourceCalculator#27]
Not all stonecutter recipes are listed.
(I know I could do this myself but I'm tired, apathetic, and already working on something so no)

**Comment by AsherGlick** [comment]
Do you think all the stonecutter recipes should be listed as the default recipe for the block they are creating? I think definitely for stairs because it ends up giving a better conversion ratio but I am not solidly on one side or the other for things like cut blocks, slabs, etc.

**Comment by AsherGlick** [comment]
The stone cutter recipes, to the best of my ability, have been added to the calculator. If you notice anything missing go ahead and reopen this bug or if it is something small create a quick PR.
