### ISSUE TITLE
Snowball stack size is 64 and not 16

### ISSUE THREAD

**Issue by smartin1018** [AsherGlick/ResourceCalculator#4]
Snowballs are thought of having a stack size of 64 and not 16 in the "Text Instructions"

**Comment by AsherGlick** [comment]
Gotta love closing old bugs. Resource calculator now supports unique stack sizes, the correct sizes have been given to the minecraft items that only have a stack size of 16.

![Screenshot from 2021-04-16 23-30-08](https://user-images.githubusercontent.com/603989/115101671-b54b4e00-9f0b-11eb-9da3-4f77a209b7d1.png)
