### ISSUE TITLE
failing to build

### ISSUE THREAD

**Issue by 1Euro7Cent** [AsherGlick/ResourceCalculator#51]
![image](https://user-images.githubusercontent.com/67194495/139588014-f2196fe5-701c-4c31-a923-32ff2034087e.png)

The error says that the file was not found.
I just downloaded it and tried to run it.

I am on Windows BTW

**Comment by AsherGlick** [comment]
I am not on windows but it looks like the file it cannot find is `tsc` which is the node typescript compiler. Did you install all the dependencies properly?

Another windows contributor also provide a usable Dockerfile specifically to make compiling on windows easier.  You can find the instructions at the end of the README.md file.

**Comment by 1Euro7Cent** [comment]
I did install all dependencies and everything installed successfully

**Comment by AsherGlick** [comment]
Then I would check that the file `node_modules/.bin/tsc` exists, if not then maybe try using the docker container instead, other windows devs have had success there. I unfortunately cannot debug windows build issues.

**Comment by 1Euro7Cent** [comment]
The file is there: 
![image](https://user-images.githubusercontent.com/67194495/139710643-bd006793-c9aa-4aa1-89b1-6f0811755de9.png)

I even tried like brute forcing to get this working, but I still didn't really succeed

**Comment by AsherGlick** [comment]
Did the docker build process work?
