### ISSUE TITLE
Litematica Upload

### ISSUE THREAD

**Issue by yoyo3841** [AsherGlick/ResourceCalculator#74]
Have a way to upload the material list that litematica generates to fill all the items in automatically rather than having to go through and do it yourself

**Comment by AsherGlick** [comment]
This is available via a fully community built and maintained plugin.
You can access it at https://resourcecalculator.com/minecraft/plugins/litematica/
Hopefully it fits your needs.

**Comment by yoyo3841** [comment]
Oh yes, thank you. Exactly what I was looking for :)
