### ISSUE TITLE
build.py taking ages to build

### ISSUE THREAD

**Issue by Adam-Albu** [AsherGlick/ResourceCalculator#83]
I ran `python build.py` --watch and after 10 minutes, it still hadn't finished.

**Comment by AsherGlick** [comment]
Using `--watch` makes the process continue running forever, automatically rebuilding whenever a file changes. This is useful if you want to continuously make changes and not have to re-run `build.py` during those changes. If you want the build process to exit when it is done then do not include the `--watch` flag.

**Comment by adamalbu** [comment]
Ok, thanks.

**Comment by AsherGlick** [comment]
If this solved your question you may close this issue.
