### ISSUE TITLE
Minecraft: Cut Copper Blocks (all variants) don't use the stone cutter

### ISSUE THREAD

**Issue by mmodrow** [AsherGlick/ResourceCalculator#89]
I noticed, that when crafting cut copper stuff, they won't be cut by default, but crafted, resulting in about 4x the copper requirement. Probably the code should either check for the cheapest option or the order in the resource yaml should be switched.

**Comment by AsherGlick** [comment]
The answer here is to swap the order of the recipes in the yaml file. I had given some thought to how I could automate sorting the recipes, however I could not come up with a good universal solution to the problem of "what is cheapest" so I decided to leave it as a manual process. Probably a script could be written to determine if any recipe was strictly better then the existing default.

**Comment by AsherGlick** [comment]
There was a big update to a bunch of cutter recipes that seems to have hit all of these. They should all be using the stonecutter now.
